In [1]:
import numpy as np
import pandas as pd

In [2]:
optimal_acc_np = np.load('./version3/acc3.npy')
file_list=np.load('./version3/file_list3.npy')

In [3]:
optimal_acc_np

array([0.9183, 0.9068, 0.8879, 0.9224, 0.8919, 0.8353, 0.8429, 0.9225,
       0.9118, 0.8848, 0.8278, 0.9225, 0.8656, 0.814 , 0.9253, 0.9034,
       0.8939, 0.883 , 0.8627, 0.8601, 0.8669, 0.9257, 0.9321, 0.905 ,
       0.8652, 0.8262, 0.9328, 0.9075, 0.8735, 0.9319, 0.9119, 0.8925,
       0.9297, 0.9061, 0.8631, 0.9327, 0.9199, 0.908 , 0.8896, 0.8495,
       0.9361, 0.8596, 0.8526, 0.8367, 0.933 , 0.843 , 0.9224, 0.9052,
       0.8994, 0.86  , 0.9392, 0.9191, 0.945 , 0.9264, 0.9389, 0.8624,
       0.8646, 0.9389, 0.8414, 0.9158, 0.9178, 0.9007, 0.8919, 0.9358,
       0.9012, 0.8623, 0.8628, 0.9408, 0.8083, 0.9267, 0.881 , 0.8477,
       0.9431, 0.9162, 0.8641, 0.9026, 0.8784, 0.8424, 0.9401, 0.9263,
       0.907 , 0.8802, 0.9429, 0.8675, 0.853 , 0.9432, 0.812 , 0.936 ,
       0.789 , 0.9207, 0.9136, 0.9021, 0.9375, 0.9461, 0.934 , 0.9147,
       0.9436, 0.8369, 0.9151, 0.8929, 0.9418, 0.9328, 0.9364, 0.8127,
       0.9032, 0.8531, 0.859 , 0.8584, 0.9447, 0.8238, 0.9358, 0.8171,
      

In [4]:
max(optimal_acc_np)

0.9535

In [5]:
max_list=np.argmax(optimal_acc_np)
max_list

164

In [6]:
file_list[199]

'Continous_2weeks_57day_1term.xlsx'

In [7]:
x=np.sort(optimal_acc_np)[::-1]

In [8]:
x

array([0.9535, 0.953 , 0.9524, 0.952 , 0.9509, 0.9508, 0.9507, 0.9503,
       0.9496, 0.9494, 0.9493, 0.949 , 0.9489, 0.9489, 0.9487, 0.9485,
       0.9485, 0.9484, 0.9482, 0.9479, 0.9477, 0.9477, 0.9473, 0.9472,
       0.9472, 0.947 , 0.9469, 0.9469, 0.9466, 0.9464, 0.9461, 0.9457,
       0.9456, 0.9456, 0.9455, 0.9451, 0.9451, 0.945 , 0.945 , 0.9449,
       0.9449, 0.9448, 0.9447, 0.9447, 0.9443, 0.9442, 0.944 , 0.9436,
       0.9435, 0.9432, 0.9432, 0.9431, 0.9429, 0.9427, 0.9427, 0.9421,
       0.942 , 0.942 , 0.9418, 0.9415, 0.9412, 0.941 , 0.9408, 0.9408,
       0.9405, 0.9401, 0.94  , 0.9399, 0.9392, 0.939 , 0.9389, 0.9389,
       0.9387, 0.9383, 0.9383, 0.9379, 0.9375, 0.9369, 0.9367, 0.9365,
       0.9364, 0.9362, 0.9361, 0.9361, 0.936 , 0.9358, 0.9358, 0.9355,
       0.9344, 0.9343, 0.934 , 0.9337, 0.9336, 0.9335, 0.9331, 0.933 ,
       0.9328, 0.9328, 0.9327, 0.9323, 0.9321, 0.9321, 0.9319, 0.9312,
       0.9301, 0.9297, 0.9296, 0.9296, 0.9292, 0.9284, 0.928 , 0.9274,
      

In [9]:
for i in x:
    list_index=np.where(optimal_acc_np==i)
    print(file_list[list_index])

['Continous_2weeks_50day_1term.xlsx']
['Continous_2weeks_49day_1term.xlsx']
['Continous_2weeks_84day_1term.xlsx']
['Continous_2weeks_75day_1term.xlsx']
['Continous_2weeks_48day_1term.xlsx']
['Continous_2weeks_78day_1term.xlsx']
['Continous_2weeks_46day_1term.xlsx']
['Continous_2weeks_62day_1term.xlsx']
['Continous_2weeks_65day_1term.xlsx']
['Continous_2weeks_71day_1term.xlsx']
['Continous_2weeks_70day_1term.xlsx']
['Continous_2weeks_58day_1term.xlsx']
['Continous_2weeks_45day_1term.xlsx' 'Continous_2weeks_68day_1term.xlsx']
['Continous_2weeks_45day_1term.xlsx' 'Continous_2weeks_68day_1term.xlsx']
['Continous_2weeks_47day_1term.xlsx']
['Continous_2weeks_73day_1term.xlsx' 'Continous_2weeks_77day_1term.xlsx']
['Continous_2weeks_73day_1term.xlsx' 'Continous_2weeks_77day_1term.xlsx']
['Continous_2weeks_85day_1term.xlsx']
['Continous_2weeks_41day_1term.xlsx']
['Continous_2weeks_40day_1term.xlsx']
['Continous_2weeks_39day_1term.xlsx' 'Continous_2weeks_69day_1term.xlsx']
['Continous_2weeks_39d

In [26]:
list_index=np.where(file_list=='Continous_2weeks_10day_1term.xlsx')
print(list_index)

(array([0], dtype=int64),)


In [29]:
optimal_acc_np[list_index]

InvalidIndexError: (array([0], dtype=int64),)

In [12]:
list_index=np.where(file_list =='Continous_2weeks_2day_1term.xlsx')


optimal_acc_np[list_index]

array([0.9026])

### 데이터 프레임으로 변환

In [13]:
type(file_list)

numpy.ndarray

In [32]:
file_list_df = pd.DataFrame(file_list)
optimal_acc_np_df = pd.DataFrame(optimal_acc_np)

In [33]:
result=pd.concat([file_list_df, optimal_acc_np], axis=1) 

In [34]:
file_list

array(['Continous_2weeks_10day_1term.xlsx',
       'Continous_2weeks_10day_2term.xlsx',
       'Continous_2weeks_10day_4term.xlsx',
       'Continous_2weeks_11day_1term.xlsx',
       'Continous_2weeks_11day_3term.xlsx',
       'Continous_2weeks_11day_9term.xlsx',
       'Continous_2weeks_12day_10term.xlsx',
       'Continous_2weeks_12day_1term.xlsx',
       'Continous_2weeks_12day_2term.xlsx',
       'Continous_2weeks_12day_5term.xlsx',
       'Continous_2weeks_13day_13term.xlsx',
       'Continous_2weeks_13day_1term.xlsx',
       'Continous_2weeks_14day_12term.xlsx',
       'Continous_2weeks_14day_14term.xlsx',
       'Continous_2weeks_14day_1term.xlsx',
       'Continous_2weeks_14day_2term.xlsx',
       'Continous_2weeks_14day_3term.xlsx',
       'Continous_2weeks_14day_4term.xlsx',
       'Continous_2weeks_14day_6term.xlsx',
       'Continous_2weeks_14day_7term.xlsx',
       'Continous_2weeks_14day_8term.xlsx',
       'Continous_2weeks_15day_1term.xlsx',
       'Continous_2weeks_16d

In [35]:
data_df = pd.DataFrame(result)

In [31]:
data_df

0       0
0     Continous_2weeks_10day_1term.xlsx  0.9183
1     Continous_2weeks_10day_2term.xlsx  0.9068
2     Continous_2weeks_10day_4term.xlsx  0.8879
3     Continous_2weeks_11day_1term.xlsx  0.9224
4     Continous_2weeks_11day_3term.xlsx  0.8919
..                                  ...     ...
403  Continous_2weeks_97day_17term.xlsx  0.8395
404   Continous_2weeks_97day_1term.xlsx  0.9415
405   Continous_2weeks_97day_5term.xlsx  0.8983
406  Continous_2weeks_97day_85term.xlsx  0.7101
407    Continous_2weeks_9day_1term.xlsx  0.9248

[408 rows x 2 columns]

In [36]:
data_df.to_excel('./version3/408case_acc.xlsx', index=False)